UILabel *label13 = [[UILabel alloc] initWithFrame:CGRectMake(15.0, 130.0, 130.0, 29.0)];
label13.adjustsFontSizeToFitWidth = NO;
label13.alpha = 1.000;
label13.autoresizesSubviews = YES;
label13.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
label13.baselineAdjustment = UIBaselineAdjustmentAlignBaselines;
label13.clearsContextBeforeDrawing = YES;
label13.clipsToBounds = YES;
label13.contentMode = UIViewContentModeLeft;
label13.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
label13.enabled = YES;
label13.frame = CGRectMake(15.0, 130.0, 130.0, 29.0);
label13.hidden = NO;
label13.highlightedTextColor = [UIColor colorWithWhite:1.000 alpha:1.000];
label13.lineBreakMode = UILineBreakModeTailTruncation;
label13.minimumFontSize = 0.000;
label13.multipleTouchEnabled = NO;
label13.numberOfLines = 1;
label13.opaque = NO;
label13.shadowOffset = CGSizeMake(0.0, -1.0);
label13.tag = 0;
label13.text = @"Carnes";
label13.textAlignment = UITextAlignmentLeft;
label13.textColor = NSNamedColorSpace iPhoneSDK darkTextColor;
label13.userInteractionEnabled = NO;

UIResponder *responder2 = [[NSProxy alloc] init];

UIView *view19 = [[UIView alloc] initWithFrame:CGRectMake(0.0, 0.0, 160.0, 159.0)];
view19.alpha = 1.000;
view19.autoresizesSubviews = YES;
view19.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleTopMargin | UIViewAutoresizingFlexibleBottomMargin;
view19.backgroundColor = [UIColor colorWithWhite:0.000 alpha:0.000];
view19.clearsContextBeforeDrawing = YES;
view19.clipsToBounds = YES;
view19.contentMode = UIViewContentModeScaleToFill;
view19.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
view19.frame = CGRectMake(0.0, 0.0, 160.0, 159.0);
view19.hidden = NO;
view19.multipleTouchEnabled = NO;
view19.opaque = YES;
view19.tag = 0;
view19.userInteractionEnabled = YES;

UITableViewCell *tableviewcell4 = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"UITableViewCellReuseIdentifier"];
tableviewcell4.accessoryType = UITableViewCellAccessoryNone;
tableviewcell4.alpha = 1.000;
tableviewcell4.autoresizesSubviews = YES;
tableviewcell4.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleTopMargin | UIViewAutoresizingFlexibleBottomMargin;
tableviewcell4.backgroundColor = [UIColor colorWithRed:0.792 green:0.792 blue:0.792 alpha:1.000];
tableviewcell4.clearsContextBeforeDrawing = YES;
tableviewcell4.clipsToBounds = NO;
tableviewcell4.contentMode = UIViewContentModeScaleToFill;
tableviewcell4.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
tableviewcell4.editingAccessoryType = UITableViewCellAccessoryNone;
tableviewcell4.frame = CGRectMake(0.0, 0.0, 320.0, 160.0);
tableviewcell4.hidden = NO;
tableviewcell4.indentationLevel = 0;
tableviewcell4.indentationWidth = 10.000;
tableviewcell4.multipleTouchEnabled = NO;
tableviewcell4.opaque = YES;
tableviewcell4.selectionStyle = UITableViewCellSelectionStyleBlue;
tableviewcell4.shouldIndentWhileEditing = YES;
tableviewcell4.showsReorderControl = NO;
tableviewcell4.tag = 0;
tableviewcell4.userInteractionEnabled = YES;

UIImageView *imageview9 = [[UIImageView alloc] initWithFrame:CGRectMake(0.0, 0.0, 160.0, 160.0)];
imageview9.alpha = 1.000;
imageview9.autoresizesSubviews = YES;
imageview9.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
imageview9.clearsContextBeforeDrawing = YES;
imageview9.clipsToBounds = NO;
imageview9.contentMode = UIViewContentModeScaleToFill;
imageview9.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
imageview9.frame = CGRectMake(0.0, 0.0, 160.0, 160.0);
imageview9.hidden = NO;
imageview9.highlighted = NO;
imageview9.multipleTouchEnabled = NO;
imageview9.opaque = YES;
imageview9.tag = 0;
imageview9.userInteractionEnabled = NO;

UIImageView *imageview8 = [[UIImageView alloc] initWithFrame:CGRectMake(0.0, 0.0, 160.0, 160.0)];
imageview8.alpha = 1.000;
imageview8.autoresizesSubviews = YES;
imageview8.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
imageview8.clearsContextBeforeDrawing = YES;
imageview8.clipsToBounds = NO;
imageview8.contentMode = UIViewContentModeScaleToFill;
imageview8.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
imageview8.frame = CGRectMake(0.0, 0.0, 160.0, 160.0);
imageview8.hidden = NO;
imageview8.highlighted = NO;
imageview8.multipleTouchEnabled = NO;
imageview8.opaque = YES;
imageview8.tag = 0;
imageview8.userInteractionEnabled = NO;

UILabel *label14 = [[UILabel alloc] initWithFrame:CGRectMake(15.0, 130.0, 130.0, 29.0)];
label14.adjustsFontSizeToFitWidth = NO;
label14.alpha = 1.000;
label14.autoresizesSubviews = YES;
label14.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
label14.baselineAdjustment = UIBaselineAdjustmentAlignBaselines;
label14.clearsContextBeforeDrawing = YES;
label14.clipsToBounds = YES;
label14.contentMode = UIViewContentModeLeft;
label14.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
label14.enabled = YES;
label14.frame = CGRectMake(15.0, 130.0, 130.0, 29.0);
label14.hidden = NO;
label14.highlightedTextColor = [UIColor colorWithWhite:1.000 alpha:1.000];
label14.lineBreakMode = UILineBreakModeTailTruncation;
label14.minimumFontSize = 0.000;
label14.multipleTouchEnabled = NO;
label14.numberOfLines = 1;
label14.opaque = NO;
label14.shadowOffset = CGSizeMake(0.0, -1.0);
label14.tag = 0;
label14.text = @"Carnes";
label14.textAlignment = UITextAlignmentLeft;
label14.textColor = NSNamedColorSpace iPhoneSDK darkTextColor;
label14.userInteractionEnabled = NO;

UIView *view20 = [[UIView alloc] initWithFrame:CGRectMake(160.0, 0.0, 160.0, 159.0)];
view20.alpha = 1.000;
view20.autoresizesSubviews = YES;
view20.autoresizingMask = UIViewAutoresizingFlexibleLeftMargin | UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleTopMargin | UIViewAutoresizingFlexibleBottomMargin;
view20.backgroundColor = [UIColor colorWithWhite:0.000 alpha:0.000];
view20.clearsContextBeforeDrawing = YES;
view20.clipsToBounds = YES;
view20.contentMode = UIViewContentModeScaleToFill;
view20.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
view20.frame = CGRectMake(160.0, 0.0, 160.0, 159.0);
view20.hidden = NO;
view20.multipleTouchEnabled = NO;
view20.opaque = YES;
view20.tag = 0;
view20.userInteractionEnabled = YES;

(null) *(null)1 = [[NSProxy alloc] init];

[view19 addSubview:imageview8];
[view19 addSubview:label13];
[tableviewcell4 addSubview:view19];
[view20 addSubview:imageview9];
[view20 addSubview:label14];
[tableviewcell4 addSubview:view20];
